services:
  - type: web
    name: contact-form-backend
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: EMAIL_USER
        value: your_email@gmail.com
      - key: EMAIL_PASS
        value: your_16_digit_app_password
